### ISSUE TITLE
env.Execute("foo.exe") , but DON'T wait for foo?

### ISSUE THREAD

**Issue by TwatBurglar** [platformio/platformio-docs#109]
env.Execute("foo.exe") - any ideas how to launch foo.exe, but continue without waiting for foo.exe (or it's children) to finish?

env.Execute is of course in extra_script.py.  foo.exe happens to be a serial monitor, which is supposed to stay running.... but env.Execute waits forever for foo.exe to exit.    I've tried every manner of 
"foo.exe", or ,
env.Execute("foo.bat"), which calls foo.exe, or,
env.Execute("start foo.bat"),  env.Execute(c:\windows\system32\cmd /C foo.exe) - /C /SEPARATE  CALL START - I've tried everything:  env.Execute stubbornly refuses to continue until everything exits.  How can I get around this?

**Comment by ivankravets** [comment]
You need this https://docs.python.org/2/library/threading.html
