### ISSUE TITLE
Quick start documentation is out-of-date

### ISSUE THREAD

**Issue by ademuri** [platformio/platformio-docs#115]
The [quick start documentation](https://docs.platformio.org/en/latest/quickstart.html) refers to `platformio project init`. However, the latest version of PIO (v4.1.0) doesn't have the `project` command anymore.

**Comment by ivankravets** [comment]
PlatformIO Core 4.2 is out! Please upgrade https://community.platformio.org/t/platformio-core-4-2/11980/3
