### ISSUE TITLE
Some issue about platform nuclei document

### ISSUE THREAD

**Issue by fanghuaqi** [platformio/platformio-docs#116]
Hi @valeros  @ivankravets,

First thank you very much for adding our Nuclei Platform into your official documentation, and do some many fixes into your platform-nuclei repo, which really help us a lot.

Here I reviewed the documentation about Platform Nuclei, I found some very tiny issues list below, hope you can fix it:
* In the board pages, for the debugger support, HummingBird Evaluation Kit current don't support `jlink` debugger, I have tested it, but it couldn't be supported. 

![图片](https://user-images.githubusercontent.com/1538922/74209457-ca529e80-4cc2-11ea-8c9d-c645b8015199.png)

* I also see these duplicated `rv-link` in three supported boards page, such as follow:
```
    jlink
    rv-link
    rv-link
```

Thanks
Huaqi

**Comment by ivankravets** [comment]
Resolved in https://github.com/Nuclei-Software/platform-nuclei/commit/4978b13018d6aca84e392c226c1b28883f6c9170

So, you will be able to configure upload protocols and debug tools per board now.
