### ISSUE TITLE
Development Platform page has broken link

### ISSUE THREAD

**Issue by bbbakke** [platformio/platformio-docs#123]
“Custom Development Platform” link on the Development Platforms page (https://docs.platformio.org/en/latest/platforms/index.html) is broken. It points to https://platformio.org/platforms/creating_platform.html which returns a 404 not found. I think it should be pointing to https://docs.platformio.org/en/latest/platforms/custom_platform_and_board.html instead.

**Comment by ivankravets** [comment]
Thanks, fixed!
