### ISSUE TITLE
Creating new project in CLion doesn't work

### ISSUE THREAD

**Issue by gbaranski** [platformio/platformio-docs#124]
CLion version 2019.3.5 x64, doesn't work on both Windows 10 and Mac os catalina, shows "Gathering info..." and on bottom "PlatformIO utility is not found". I can't find any fix
![image](https://user-images.githubusercontent.com/34353640/77967156-d8956200-72e4-11ea-9c1c-e406e23aadc7.png)

**Comment by ivankravets** [comment]
This is a known issue, we requested this feature here  https://youtrack.jetbrains.com/issue/CPP-19412
CLion does not install PlatformIO Core automatically for you:

1. [Install PlatformIO Core](https://docs.platformio.org/en/latest/core/installation.html#installation-methods) using installation script
2. [Install Shell Comamnds](https://docs.platformio.org/en/latest/core/installation.html#install-shell-commands)

So, you should have working `platformio --version` command when opening the system terminal or after the restart of your OS. You need to patch the PATH system environment variable and extend it with a folder where PlatformIO Core is installed. We don't have SUDO/Administrative permissions. As a result, we can't do this for you.

The other option is to install [PlatformIO IDE for VSCode](https://docs.platformio.org/en/latest/integration/ide/vscode.html), it will install PlatformIO Core automatically for you. You will just need to path the system PATH and switch back to CLion.

/cc @anastasiak2512 @elmot

**Comment by gbaranski** [comment]
Awesome, thanks :)

**Comment by ivankravets** [comment]
Does it work now?

**Comment by gbaranski** [comment]
@ivankravets that works, now I'm trying to figure how to fix syntax highlithing, CLion doesn't see default Arduino.h library

**Comment by elmot** [comment]
@gbaranski ensure that your files are c++ (i.e. have .cpp extension)

**Comment by Sukikui** [comment]
> 

Hello, can you more precisely explain how to "path the system PATH" ? I met the same problem and nothing work, but I've PIO Core thanks to VSCode, from this I don't know how to link the packages with CLion.

**Comment by VA7ODR** [comment]
I also encountered the issue where it always says "Gathering info..." forever if you try to create a new PlatformIO project while currently editing another.  If you close all extra instances, and switch the remaining CLion instance to a Non-PlatformIO project, then create the new one, it instantly shows the board list.

**Comment by biryusal** [comment]
> I also encountered the issue where it always says "Gathering info..." forever if you try to create a new PlatformIO project while currently editing another. If you close all extra instances, and switch the remaining CLion instance to a Non-PlatformIO project, then create the new one, it instantly shows the board list.

I just don't know what to say...
You saved me days of work!

I really had to close the previous project (that was also created via `PlatformIO`) and then the endless `Gathering info` has gone


thank you so much!

> I also encountered the issue where it always says "Gathering info..." forever if you try to create a new PlatformIO project while currently editing another. If you close all extra instances, and switch the remaining CLion instance to a Non-PlatformIO project, then create the new one, it instantly shows the board list.

> I also encountered the issue where it always says "Gathering info..." forever if you try to create a new PlatformIO project while currently editing another. If you close all extra instances, and switch the remaining CLion instance to a Non-PlatformIO project, then create the new one, it instantly shows the board list.

I just don't know what to say...
You saved me days of work!

I really had to close the previous project (that was also created via `PlatformIO`) and then the endless `Gathering info` has gone


thank you so much!
