### ISSUE TITLE
Wifi Station code used as exemple

### ISSUE THREAD

**Issue by iBraesch** [platformio/platformio-docs#126]
Hi,

I followed your tutorial on getting started with PlatformIO and ESP-IDF for the ESP32: https://docs.platformio.org/en/latest/tutorials/espressif32/espidf_debugging_unit_testing_analysis.html

The code used as example is the [wifi station](https://github.com/espressif/esp-idf/blob/master/examples/wifi/getting_started/station/main/station_example_main.c) example from the ESP-IDF examples, and compiles perfectly using the provided instructions in the tutorial. However the points 6. and 7. from the section [Adding Code to the Generated Project](https://docs.platformio.org/en/latest/tutorials/espressif32/espidf_debugging_unit_testing_analysis.html#id2) relate to another example from the ESP-IDF, namely the [SoftAP](https://github.com/espressif/esp-idf/tree/master/examples/wifi/getting_started/softAP) example.

Inconsistent part:
![esp_idf_pio_LI](https://user-images.githubusercontent.com/26903796/80139994-9be91d80-85a7-11ea-9abc-e013540e2997.jpg)
With the provided code, the ESP32 acts as a station (picture in 6. displays a usage in SoftAP mode) and therefore no AP is created and no AP is to be found (as expected with picture in 7.)

Simple fix would be to provide the SoftAP example code in the tutorial.

Otherwise, thanks for the tutorial 👍 

Cheers,
Igor

**Comment by valeros** [comment]
Many tanks, fixed!
