### ISSUE TITLE
Here's a Gitlab build script

### ISSUE THREAD

**Issue by buckle2000** [platformio/platformio-docs#14]
So I just transpiled this from the Travis CI template in your doc.
https://gist.github.com/buckle2000/302e40aa0dfec81c64eebe01f14af806
Maybe it is useful.

**Comment by ivankravets** [comment]
@valeros please extend docs with CI for GitLab

**Comment by buckle2000** [comment]
@valeros 
Still some problems in the docs.

## 1

![default](https://user-images.githubusercontent.com/10850402/29927236-4a8a4166-8e98-11e7-8028-7a9e6884b42e.png)

## 2

Don't use `before_script` to install pip package!
`before_script` will run before **every** job. That's a waste of time.

## 3

You may mention that Gitlab has public linux runners, so most people don't need to setup one.

**Comment by valeros** [comment]
@buckle2000 
1. It's ok, that reference will be resolved in the real doc page.
2. Have you tried your configuration for a real project example? I've tried using `job_install` as in your snippet, but as I saw from GitLab documentation for "jobs", they are totally independent, so PlatformIO won't be visible from other jobs. Am I missing something? 
3. Feel free to add any remarks as a PR.

**Comment by buckle2000** [comment]
2. Sorry, I misunderstood something.
