### ISSUE TITLE
Obsolete PIO Core v4.3.3 is used (previous was 4.3.4)

### ISSUE THREAD

**Issue by karansoi** [platformio/platformio-docs#143]
When I compile an integration with esphome (dev) I get this warning.
The complete verbose output is
`
NFO Reading configuration /config/esphome/weighingscale.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/weighingscale
********************************************************************************
Obsolete PIO Core v4.3.3 is used (previous was 4.3.4)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system
********************************************************************************
Processing weighingscale (board: esp12e; framework: arduino; platform: espressif8266@2.2.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 2.20502.0 (2.5.2) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa 1.40802.2 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <ESPAsyncTCP-esphome> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Retrieving maximum program size /data/weighingscale/.pioenvs/weighingscale/firmware.elf
Checking size /data/weighingscale/.pioenvs/weighingscale/firmware.elf
RAM:   [=====     ]  46.3% (used 37920 bytes from 81920 bytes)
Flash: [====      ]  38.5% (used 402096 bytes from 1044464 bytes)
========================= [SUCCESS] Took 9.95 seconds =========================
`
How do I remove the multiple files from my system
I have HASSOS running of a SD Card image.

**Comment by valeros** [comment]
You've opened the issue in the wrong repository. Anyway, please try this methods https://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
