### ISSUE TITLE
Build for unsupported board with available library

### ISSUE THREAD

**Issue by sion559** [platformio/platformio-docs#144]
This isn't so much an issue as it is a question.
I have a stm32f042C6 and want to use platform IO with it, but there is no board support for this model.
The closes model is the stm32f042K6 which is the exact same chip but in a 48pin package.
Can I built my program for the K version and expect it to work on the C as well? and if so, does it support the extra pins?

**Comment by valeros** [comment]
If the only difference is the number of GPIO pins, then it should work out of the box.
