### ISSUE TITLE
Bad help #anchor for multiple cores

### ISSUE THREAD

**Issue by tablatronix** [platformio/platformio-docs#154]
```
********************************************************************************
Obsolete PIO Core v3.6.3 is used (previous was 4.3.0)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system
********************************************************************************
```

Actual doc site anchor is
https://docs.platformio.org/en/latest/faq.html#multiple-platformio-cores-in-a-system

Should be consistant , add proper anchor for links to work again

**Comment by ivankravets** [comment]
It's already fixed. You use crazy old PlatformIO Core. Please upgrade to PlatformIO Core 5.0 and remove other PIO Cores from the system. We recommend using PlatformIO IDe which comes with the latest PlatformIO Core.
