### ISSUE TITLE
Board In Arduino Debugging Tutorial does not exist

### ISSUE THREAD

**Issue by PhysicsUofRAUI** [platformio/platformio-docs#157]
I am using platformio with the atom text editor, and I am trying to follow this tutorial, https://docs.platformio.org/en/latest/tutorials/espressif32/arduino_debugging_unit_testing.html, but when I search for ESP32-DevKitC, it says no data. 

I then looked for it on this page, https://docs.platformio.org/en/latest/boards/index.html, and nothing came up. I would guess that this is why the name ESP32-DevKitC is in red instead of the blue that most links in your docs are. 

I would offer to help, but I am only just learning about this library.

**Comment by ivankravets** [comment]
@valeros please replace "static" board names with `:ref:`board_xxxx`.
