### ISSUE TITLE
Oudated documentation about setting strict_ssl

### ISSUE THREAD

**Issue by Rotzbua** [platformio/platformio-docs#159]
## Problem

Command fails.

```bash
$ platformio settings set strict_ssl yes
Error: Invalid setting with the name 'strict_ssl'
The command "platformio settings set strict_ssl yes" failed and exited with 1 during .
```

**Change or removal is NOT mentioned in documentation, migration or release notes!!**

https://docs.platformio.org/en/latest/core/history.html
https://docs.platformio.org/en/latest/core/migration.html

## Solution

Update documentation to new? setting name.

Mention rename or removal in release note....

## Reference
https://github.com/platformio/platformio-docs/blob/develop/core/userguide/cmd_settings.rst#strict-ssl

**Comment by ivankravets** [comment]
Sorry, fixed in https://github.com/platformio/platformio-docs/commit/b701762bef10ab52032b32e6721a7675534cb15f

**Comment by Rotzbua** [comment]
Thanks for clarification👍

**Comment by ivankravets** [comment]
Happy coding with PlatformIO!
