### ISSUE TITLE
Documentation for simavr with Arduino Uno Rev.3: how to get debugging info for peripherals  

### ISSUE THREAD

**Issue by DerAndere1** [platformio/platformio-docs#170]
The documentation for board uno at https://docs.platformio.org/en/latest/boards/atmelavr/uno.html#board-atmelavr-uno implies that debugging using simavr is possible with the Arduino Uno Rev3 without additional hardware. The documentation says it should work by simply adding debug_tool = simavr in platformio.ini.

I failed with the atmega-native-blink example in VSC + PlatformIO IDE with modified platformio.ini (see below):
1. Clean All
2. Build All
3. Pre-Debug All
4. In the left toolbar click "Start Debug" 
5. In the toolbar at the top, select "Debug (skip pre-debug) (<projectname>)" and click "Start Debugging" 

Observation:
The section "PERIPHERALS" in the debug view only says "No information". Having the Arduino Uno Rev3 with the uploaded firmware connected via USB does not change this. 

Here my modified platformio.ini
```
[platformio]
default_envs = unodebug

[env:uno]
platform = atmelavr
board = uno
build_type = release
upload_protocol = arduino

[env:unodebug]
platform = atmelavr
board = uno
build_type = debug
debug_tool = simavr
upload_protocol = arduino
```

**Comment by ivankravets** [comment]
There is no "peripherals" information for AVR. This is simulator, not hardware debugging.
