### ISSUE TITLE
Arduino ESP32 core issue: esp_vfs.h with littlefs

### ISSUE THREAD

**Issue by doobedoobedo** [platformio/platformio-docs#177]
The littlefs_esp32 library (both versions 1 and 1.05) fails to build with the error:
.pio/libdeps/esp32doit-devkit-v1/LittleFS_esp32/src/esp_littlefs.c:208:9: error: unknown field 'utime_p' specified in initializer

This is because the esp_vfs_t struct (~/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/vfs/esp_vfs.h) is missing the definition. Taking the definition from https://github.com/espressif/esp-idf/blob/master/components/vfs/include/esp_vfs.h (lines 206-209 at the time of reporting) and inserting it at line 184 allows the library to build at least, I've not done any further investigation.

**Comment by valeros** [comment]
That library is not supposed to work with the current stable Arduino core v1.0.4 as it depends on he latest idf-release/v4.2 branch.
