### ISSUE TITLE
RT1020 EVK with wrong memory size

### ISSUE THREAD

**Issue by enginlee** [platformio/platformio-docs#179]
Hi,

I found there are incorrect RAM/flash size defined in 'boards/nxpimxrt/mimxrt1020_evk.rst'
It should be RAM=256Mb=32MB and Flash=64Mb=8MB
Reference: https://www.nxp.com/design/development-boards/i-mx-evaluation-and-development-boards/i-mx-rt1020-evaluation-kit:MIMXRT1020-EVK
And also it reflect to the list of https://platformio.org/boards

Thanks,

**Comment by valeros** [comment]
The doc pages for boards are autogenerated. I've fixed the size in the board manifest, so the docs will be updated shortly after.
