### ISSUE TITLE
[FR] Documentation for the fact that "Clone Git Project" requires manual installation of Git  

### ISSUE THREAD

**Issue by DerAndere1** [platformio/platformio-docs#182]
I could not find information that a manual installation of Git (https://git-scm.com/) is required if the user wants to use "Clone Git Project" 

**My steps:** 
-No installation of Git
- while Git is not installed, click on "PlatformIO" in left tool bar. In panel "PLATFORMIO", click "QUICK ACCESS" -> "Miscellaneous" -> Clone Git Project".

**Current result:** 
Nothing happens

**Expected result:**
- Pop-up notification that Git has to be installed and added to the PATH System environment variable in order to use "Clone Git Project"
- In section "installation" of the Getting Started document at https://docs.platformio.org/en/latest/integration/ide/vscode.html#id1 it should be mentioned that installation of Git and addition to the PATH Sytem environment variable is required to have access to all features of the Platform IDE

**Comment by ivankravets** [comment]
@valeros please add `:note` that Git is required for `Clone Git Project` command. Add also a link where to download it.
