### ISSUE TITLE
Proposal link for new library

### ISSUE THREAD

**Issue by aelray** [platformio/platformio-docs#184]
Proposal link for new library leads to archived [Github repository issue tracker](https://github.com/platformio/platformio-libmirror/issues).
![image](https://user-images.githubusercontent.com/2736151/110686816-234f7780-81e0-11eb-859d-edce68b6a6a2.png)

**Comment by ivankravets** [comment]
Thanks, fixed!

**Comment by aelray** [comment]
Nice. But not actually the kind of fix that I was looking for. Is there some kind of documentation or support to wrap something which is already available as a PIO library? I am using [ERPC](https://github.com/EmbeddedRPC/erpc) in a legacy zephyr project and wanted to make it available as PIO library to move the whole project to PIO.

**Comment by ivankravets** [comment]
Please file a feature request at https://github.com/EmbeddedRPC/erpc/issues
