### ISSUE TITLE
Is OpenThread still not supported in Zephyr RTOS?

### ISSUE THREAD

**Issue by FlomoN** [platformio/platformio-docs#210]
Hey, I would like to start a project with Zephyr RTOS and NRF52840 to play around with OpenThread, but what's holding me off is that the documentation says the OpenThread module of Zephyr RTOS is not supported in PlatformIO.

https://docs.platformio.org/en/latest/frameworks/zephyr.html#limitations

However, I also found [this](https://community.platformio.org/t/native-support-for-zephyr-2-2-0/12804) announcement from April 2020 that claims "native support for OpenThread module".
In 9828594e7b8dcea50712af45341850cf1659031a the limitations section wasn't updated either.

Has this been forgotten?

I would really love to develop OpenThread projects with PlatformIO.

Kind Regards,
FlomoN

**Comment by valeros** [comment]
Hi @FlomoN ! It's supported, here is [an example](https://github.com/platformio/platform-nordicnrf52/tree/develop/examples/zephyr-net-echo-client) with OpenThread enabled.
