### ISSUE TITLE
Expose `--skip-packages` option in GUI

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platformio-docs#217]
The PIO Home -> Inspect screen should have an option that makes it so that `--skip-packages` is passed to `pio check`, otherwise ESP32, ESP8266 and SAMD based projects (and possible others) cannot be code-inspected in the UI because `cppcheck` fails.

See https://github.com/platformio/platformio-core/issues/3951 and https://community.platformio.org/t/code-inspection-not-returning-expected-result/21480.

**Comment by ivankravets** [comment]
Sorry, it is our bug. We will update our docs.

**Comment by jerabaul29** [comment]
Same problem with Sparkfun Artemis using the core from nigelb.

**Comment by GuyZou** [comment]
Please, Fix-it ...

**Comment by maxgerhardt** [comment]
See https://github.com/platformio/platformio-core/issues/3951#issuecomment-993968462 for a `platformio.ini`-side fix, this should work with the GUI too.
