### ISSUE TITLE
Config option names outdated

### ISSUE THREAD

**Issue by Tretgo** [platformio/platformio-docs#218]
The build options have been renamed from "build" to "board_build".

This is not reflected in the documentation, at least for STM32cube framework.

![grafik](https://user-images.githubusercontent.com/59660352/141855909-5840054b-1f62-48cf-b6fc-c10e922fe337.png)

`Warning! Ignore unknown configuration option `build.stm32cube.disable_embedded_libs` in section [env:robotdyn_blackpill_f303cc]`

Using board_build.stm32cube.disable_embedded_libs = yes works as intended

**Comment by valeros** [comment]
Many thanks, fixed!
