### ISSUE TITLE
Better explanation for the initial upload for ESP OTA.

### ISSUE THREAD

**Issue by HubKing** [platformio/platformio-docs#222]
If you search Google, it shows [this page](https://docs.platformio.org/en/latest/platforms/espressif8266.html#over-the-air-ota-update). I, like most people, already know the basic idea of OTA, and just wanted to know the instructions to enable it on the ESP. But the documentation, instead of give the concise information about the preparation step,  just tells the user to read the "What is OTA? How to use it?" link.

That leads users to a very length web page. The problem is that the page only explanations the step for the Arduino IDE. It asks the user to run the BasicOTA.ini under examples, but Platform IO has no such menu. After watching the lengthy linked YouTube video, I heard that the video author has [his own documentation page](https://www.penninkhof.com/2015/12/1610-over-the-air-esp8266-programming-using-platformio/). In that page, it has link for the BasicOTA.ini file. 

Either the PlatformIO's documentation page should link [that page](https://www.penninkhof.com/2015/12/1610-over-the-air-esp8266-programming-using-platformio/) right below "Firstly, please read What is OTA? How to use it?" or add concise explanation for the steps to upload the initial binary using PlatformIO, not the Arduino IDE.

**Comment by ivankravets** [comment]
@valeros please add a link to https://github.com/esp8266/Arduino/blob/master/libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino
