### ISSUE TITLE
Possible missing documentation for "Used by" dependents on library.json manifiest

### ISSUE THREAD

**Issue by hpsaturn** [platformio/platformio-docs#226]
Hi,

First, thanks for awesome job on the last version of PlatformIO registry. It is a so good improvement. 

One question, maybe is missing the documentation for the field "used by" on the [current documentation](https://docs.platformio.org/en/latest/librarymanager/config.html#dependencies)? Or how I can fill this field:

![screenshot20220106_014218](https://user-images.githubusercontent.com/423856/148310016-9cffd209-39d9-462a-9de9-05f264358f13.jpg)

**Comment by ivankravets** [comment]
Hi,

Thanks for the kind words! 😊 

"Used by" is automatically calculated based on https://docs.platformio.org/en/latest/librarymanager/config.html#dependencies

So, if someone publishes package A that depends on package B, we track this.
