### ISSUE TITLE
Sanguino docs still point to old repository

### ISSUE THREAD

**Issue by Lauszus** [platformio/platformio-docs#23]
PlatformIO moved to using my repository in: https://github.com/platformio/platformio-core/issues/586.

However the docs are still pointing to the old repository: http://docs.platformio.org/en/latest/platforms/atmelavr.html#sanguino.

**Comment by ivankravets** [comment]
Thanks! updated!

**Comment by Lauszus** [comment]
Thanks. You forgot to remove the ```?utm_source=platformio&utm_medium=docs``` part from all the links though.

**Comment by ivankravets** [comment]
Docs generator adds them automatically. The links are valid

**Comment by Lauszus** [comment]
Ahh cool, no worries then :)
