### ISSUE TITLE
Can Platformio build for the nordic nrf52 Particle Argon Zephyr?

### ISSUE THREAD

**Issue by rpbissonnette** [platformio/platformio-docs#248]
It seems that 
.platformio/platforms/nordicnrf52/builder/main.py
line 142
                     board.get("build.softdevice.sd_fwid"),
is looking for a softdevice entry in 
.platformio/platforms/nordicnrf52/boards/particle_argon.json

There IS such an entry for the Xenon, though I have no idea what it is for
.platformio/platforms/nordicnrf52/boards/particle_xenon.json

I am looking at a fresh install, but I don't see version etc. aside from 
Core 6.0.2·Home 3.4.1

Thank you.

**Comment by ivankravets** [comment]
Please forward questions to https://community.platformio.org/
