### ISSUE TITLE
 Could not find compatible Python 3.6 or above in your system

### ISSUE THREAD

**Issue by Misaka15535** [platformio/platformio-docs#251]
(py36) C:\Users\me\Desktop\new>python3.exe get-platformio.py
C:\Users\me\Desktop\new\.piocore-installer-v565tt5u
Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.10 (main, Mar 14 2022, 18:37:07)  [GCC 11.2.0 64 bit (AMD64)]
Python path: G:\msys64\mingw64\bin\python3.exe
Creating a virtual environment at C:\Users\me\.platformio\penv
Error: Could not find compatible Python 3.6 or above in your system.Please install the latest official Python 3 and restart installation:
https://docs.platformio.org/page/faq.html#install-python-interpreter

(py3_8) C:\Users\me\Desktop\新建文件夹>python get-platformio.py
C:\Users\me\Desktop\新建文件夹\.piocore-installer-uro0k848
Installer version: 1.1.2
Platform: Windows-10
Python version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
Python path: C:\ProgramData\Anaconda3\envs\py3_8\python.exe
Creating a virtual environment at C:\Users\me\.platformio\penv
Error: Could not find compatible Python 3.6 or above in your system.Please install the latest official Python 3 and restart installation:
https://docs.platformio.org/page/faq.html#install-python-interpreter

Weird. I also tried version 3.7, but it doesn't work. I am using anaconda python.

**Comment by ivankravets** [comment]
msys64, anaconda - these are broken and invalid Pythons. We highly recommend uninstalling Anaconda and using official Python.
