### ISSUE TITLE
Incorrect example in Googletest usage docs

### ISSUE THREAD

**Issue by Michal123456747** [platformio/platformio-docs#255]
In embedded tests, example line, that starts all tests with Mocks(commented line) should be without arguments.
https://github.com/platformio/platformio-docs/blob/develop/advanced/unit-testing/frameworks/googletest.rst

**Comment by ivankravets** [comment]
Do you mean this https://github.com/google/googletest/blob/bf66935e07825318ae519675d73d0f3e313b3ec6/googlemock/test/gmock_output_test_.cc#L279 ?

**Comment by Michal123456747** [comment]
No. In the link above is 
```
::testing::InitGoogleTest();
    // if you plan to use GMock, replace the line above with
    // ::testing::InitGoogleMock(&argc, argv);
```

instead of

```
::testing::InitGoogleTest();
    // if you plan to use GMock, replace the line above with
    // ::testing::InitGoogleMock();
```

**Comment by ivankravets** [comment]
Thanks for the report! Fixed!
