### ISSUE TITLE
Full list of built-in mbed libraries is absent

### ISSUE THREAD

**Issue by me21** [platformio/platformio-docs#26]
There is a [link](https://github.com/platformio/builder-framework-mbed/blob/develop/mbed.py#L323) to what is supposed to be a full-list of built-in mbed libraries at http://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-ignore
But the link is apparently stale.

**Comment by ivankravets** [comment]
Thanks! See https://github.com/platformio/platformio-docs/commit/7c206c57f03279271aee4c5043ea5a50b95c8edc
