### ISSUE TITLE
platforms/asrmicro650x.rst deleted

### ISSUE THREAD

**Issue by SebDominguez** [platformio/platformio-docs#262]
I came across many dead links (https://github.com/platformio/platformio-docs/blob/develop/platforms/asrmicro650x.rst)
And it seems that many documentation files where deleted. Is there a new location for them now?

**Comment by SebDominguez** [comment]
found here : https://docs.platformio.org/en/stable//platforms/asrmicro650x.html

**Comment by ivankravets** [comment]
This is a bug, please file an issue at https://github.com/HelTecAutomation/platform-asrmicro650x/issues

The docs will be removed from the `stable` branch soon.
