### ISSUE TITLE
What kind of links should I use? "/page/" or "/en/latest/"?

### ISSUE THREAD

**Issue by MacDada** [platformio/platformio-docs#275]
In my `platformio.ini` I see the link https://docs.platformio.org/page/projectconf.html -> it redirects to https://docs.platformio.org/en/latest/projectconf/index.html

I like to heavily document my code/config files, so I want to include links to the official docs.

Which kind of links should I use?

* `/page/` like https://docs.platformio.org/page/projectconf/section_platformio.html#default-envs
* `/en/latest/` like https://docs.platformio.org/en/latest/projectconf/section_platformio.html#default-envs

I guess that `/page/` might be more universal, but I don't know the reasons behind the redirects.

**Comment by ivankravets** [comment]
The `page`-type URL is a legacy format from the previous place where docs where hosted. Nevertheless, you can use any of them. I recommend using `/en/latest/`.
