### ISSUE TITLE
Compile DB example is wrong

### ISSUE THREAD

**Issue by MrAwesomeRocks** [platformio/platformio-docs#294]
https://github.com/platformio/platformio-docs/blob/eafa866b1d172513b897ebd7fd97e0c9bcbfbed8/integration/compile_commands.rst?plain=1#L48-L53

This `post` should be a `pre`, as otherwise the compilation DB is generated before the parameters are updated.

**Comment by ivankravets** [comment]
Thanks for the issue. Please make PR.

**Comment by ivankravets** [comment]
No need to make PR. Fixed in https://github.com/platformio/platformio-docs/commit/239b55f227a05e805c125462697727112829f9d1
