### ISSUE TITLE
Critical link to Jenkins tutorial dead

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platformio-docs#296]
For "Integration", the Jenkins docs

https://docs.platformio.org/en/latest/integration/ci/jenkins.html#integration

point at 

http://www.thingforward.io/techblog/2017-11-03-setting-up-a-jenkins-ci-engine-for-embedded-projects.html

the domain however as ceased to exist apperently.

The WayBackMachine still has it archived though

https://web.archive.org/web/20200922231607/http://www.thingforward.io/techblog/2017-11-03-setting-up-a-jenkins-ci-engine-for-embedded-projects.html

If possible the full instructions on how to integrate PlatformIO with Jenkins should be on that documentation page, not being dependant on an external site.

**Comment by vazhnov** [comment]
https://github.com/platformio/platformio-docs/blob/develop/integration/ci/jenkins.rst should be fixed or adjusted.
The original article at ThingForward blog wasn't opensource, so it can't just be copied into the PlatformIO documentation.
Somebody should write it from scratch…

**Comment by ivankravets** [comment]
We temporarily removed that page. We would be thankful for the new PR.
