### ISSUE TITLE
question: debugging esp32 with another esp32 

### ISSUE THREAD

**Issue by jonnytest1** [platformio/platformio-docs#300]
as the title says i was thinking of debugging my esp32 
however instead of buying a 32$ jtag probe i thought it would be cheaper to just use one of my already bought other esp32s 🤔
has anyone tried this before ? or has any insight that could help ?

**Comment by valeros** [comment]
Hi @jonnytest1 ! It's not the right place to ask such generic questions, please forward to https://community.platformio.org/. Note you can find the list of supported debug probes here https://docs.platformio.org/en/latest/plus/debugging.html#tools-debug-probes.
