### ISSUE TITLE
GoogleTest example miss #include "gmock/gmock.h" for GMock

### ISSUE THREAD

**Issue by xzxzxc** [platformio/platformio-docs#303]
In case you try to follow the following hint of the https://github.com/platformio/platformio-docs/blob/develop/advanced/unit-testing/frameworks/googletest.rst
```c++
::testing::InitGoogleTest(&argc, argv);
// if you plan to use GMock, replace the line above with
// ::testing::InitGoogleMock(&argc, argv);
```
and replace `InitGoogleTest` with `InitGoogleMock`, it will fail with an error:

> error: no member named 'InitGoogleMock' in namespace 'testing'; did you mean 'InitGoogleTest'?

To fix it, you can add
```c++
#include "gmock/gmock.h"
```
at the beginning of the file.

I'm new to embedded programming and C++ at all, so it wasn't obvious to me, and took time to figure out. I hope the fix can help someone like me.

**Comment by ivankravets** [comment]
Thanks for the issue!
