### ISSUE TITLE
build_src_filter has a bug that prevents it from filtering files in the PlatformIO system libraries.

### ISSUE THREAD

**Issue by GPTKEY** [platformio/platformio-docs#325]
build_src_filter Fails when filtering library files on the system disc where PlatformIO is located.
Is there any way to filter the files in the system library?

**Comment by valeros** [comment]
There is a multi-purpose special helper function `AddBuildMiddleware` that can be used in your case. Take a look at an example on this [doc page](https://docs.platformio.org/en/latest/scripting/middlewares.html).
