### ISSUE TITLE
Setting monitor_filters in ini file as described in the documentation does not work

### ISSUE THREAD

**Issue by marcelloDC** [platformio/platformio-docs#348]
When I set `monitor_filters` to `direct` using the  multiple lines format as described in the documentation I get the following warning when i start up the serial-monitor:

`Warning! Skipping unknown filters direct; . Known filters are colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, send_on_enter, time`

and the filter is not set. It only works when I use the "single line" format as below:

`monitor_filters = direct`

In Core 6.1.14 Home 3.4.4

**Comment by ivankravets** [comment]
> Warning! Skipping unknown filters direct; 

Wrong declaration. The format is following:

```
monitor_filters = 
   f1
   f2
   fn
```

**Comment by ivankravets** [comment]
Indeed, the `;` is a valid symbol, this is a comment identifier. However, it should be split with `space`. For example,
```ini
monitor_filters =
    direct ; my comment
```
