### ISSUE TITLE
"Debug" vs "Debug (Skip Pre-Debug)"

### ISSUE THREAD

**Issue by Navis-Raven** [platformio/platformio-docs#36]
hi, 
there is two options in the debug menu: "PIO Debug" and "PIO Debug (Skip Pre-Debug)"

![image](https://user-images.githubusercontent.com/15887222/44710891-755ea080-aaad-11e8-810a-d6ee886fc181.png)

But I didn't find in the documentaion what is the difference between each of them. The only thing which I found about pre-debug in the documentation is about the settings (release vs pre-debug):

![image](https://user-images.githubusercontent.com/15887222/44710842-595aff00-aaad-11e8-9028-2a2d8268f48a.png)

![image](https://user-images.githubusercontent.com/15887222/44710743-1d279e80-aaad-11e8-9ffc-f2152cbf07e7.png)

**Comment by ivankravets** [comment]
See new docs: http://docs.platformio.org/en/latest/ide/vscode.html#debugging

1. Please upgrade PIO Core
2. Now, default debug configuration is without "Pre-Debug"
3. defaultToolbarAction setting was removed. Use http://docs.platformio.org/en/latest/projectconf/build_configurations.html

**Comment by Navis-Raven** [comment]
Problem solved
![image](https://user-images.githubusercontent.com/15887222/45170306-dc8ff980-b1ff-11e8-9bea-2fec2cad2f16.png)
