### ISSUE TITLE
Confusing info about monitor_port

### ISSUE THREAD

**Issue by moose-on-road** [platformio/platformio-docs#362]
[monitor_port](https://github.com/platformio/platformio-docs/blob/develop/projectconf/sections/env/options/monitor/monitor_port.rst)

Having a real hard time figuring out how to use this option. There isn't enough information here. I think I want to use a URL handler, but this links to an external website for PySerial. I dont understand the relevance of this software or if the link is even intentional. I can't find PySerial in the registry, is it something I need to install seperatly?

**Comment by ivankravets** [comment]
PlatformIO Core internally uses `pyserial` module to handle such types of operations. The `pyserial` dependency is already installed with PlatformIO Core. Just use the URL format as described in its documentation.
