### ISSUE TITLE
Add a serial monitor "hello world" tutorial next to "Unit Testing of a “Blink” Project"

### ISSUE THREAD

**Issue by SDS-Emb** [platformio/platformio-docs#40]
It ll be good for new users if you add a serial monitor "hello world" tutorial next to "Unit Testing of a “Blink” Project" tutorial.

**Comment by ivankravets** [comment]
What do you mean? Please explain in details.

**Comment by Navis-Raven** [comment]
@ivankravets  I think this is issue is now solved with the new ESP-32 tutorial 
"Get started with Arduino and ESP32-DevKitC: debugging and unit testing" tutorial @ivankravets 

I just have to test the tutorial, and this will close the issue

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/tutorials/index.html
