### ISSUE TITLE
Questions about J Link installation documentation

### ISSUE THREAD

**Issue by Navis-Raven** [platformio/platformio-docs#42]
Go to this webpage: https://docs.platformio.org/en/latest/plus/debug-tools/jlink.html#debugging-tool-jlink

FIRST QUESTION: Go to Drivers/windows paragraph and apply the first step: start debug session, and see what happens : it works while it should'nt work because we didn't installed yet the driver. How it can be ? please explain.

SECOND QUESTION: This question depends of the answer of the first question.

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/plus/debug-tools/jlink.html#drivers

When you start debugging session, PlatformIO downloads depending `tool-jlink` package into `~/packages/tool-jlink`. After that, you can navigate here and install driver.

**Comment by Navis-Raven** [comment]
@ivankravets  but it's a mystery that the debug session worked without installign this downloaded driver (and I didn't even installed it before).
