### ISSUE TITLE
Detected non-PlatformIO `extra_scripts` option 

### ISSUE THREAD

**Issue by amurchick** [platformio/platformio-docs#8]
Please update docs for change `extra_scripts` to `extra_script`

**Comment by ivankravets** [comment]
`extra_script` was renamed to `extra_scripts` and supports multiple scripts, not just a one. This is a new feature of PIO Core 3.4.1. See docs http://docs.platformio.org/en/latest/projectconf/section_env_advanced.html#extra-scripts
