### ISSUE TITLE
Include instructions on how to update the development version of PlatformIO

### ISSUE THREAD

**Issue by SwiftWinds** [platformio/platformio-docs#85]
### Context
1. installed latest development version with `pip install -U https://github.com/platformio/platformio-core/archive/develop.zip` to a venv
2. added it to my PATH 

### Question
To update it, I'm confused whether I do:

1. `pip install -U platformio`
2. `pip install -U https://github.com/platformio/platformio-core/archive/develop.zip`
3. something else completely different?

Maybe you could please **update the docs on how to update development version of PlatformIO** or if you **explain it to me**, I can submit a PR to update the docs.

Thanks!

**Comment by ivankravets** [comment]
Every time when you repeat `pip install -U https://github.com/platformio/platformio-core/archive/develop.zip`, it upgrades to the latest version from Github. Alternative shortcut is http://docs.platformio.org/en/latest/userguide/cmd_upgrade.html#cmdoption-platformio-upgrade-dev

```
pio upgrade --dev
```

This is actually what I use very often on test machines.
