### ISSUE TITLE
Docs include features for unreleased versions

### ISSUE THREAD

**Issue by LongLiveCHIEF** [platformio/platformio-docs#90]
**Problem**: Docs include features that are not yet available in release versions of PIO Core, and have a `version added: X.Y`, which implies that version is _released_ and causes users to spend time figuring out why everything is "up to date", even though their version is lower than what is referenced in docs.

**Example**: The `extends` option(https://github.com/platformio/platformio-docs/commit/90af5feac507b7c593570149e0aa789d389df498) says it was impemented in `4.1.0`.  I spent at least 30 minutes trying to figure out why every install method I tried would only install `4.0.3`, when the docs implied that the latest was _at least_ `4.1`.

After a while, i ran across an obscure issue thread that mentioned running `pio upgrade --dev`, which install 4.1 _release candidate_.  

Can we either:
- hold off on publishing features to production docs until they've officially been released
- find a way to auto-stye non-released versions so they get a special label until that version has hit prod
- include a link to using the `--dev` flag on any feature that is published to prod docs before corresponding core is released?

**Comment by valeros** [comment]
Hi @LongLiveCHIEF ! Thanks for reporting. You can switch to [the stable version of the documentation](https://docs.platformio.org/en/stable/) which includes only released features.
![docs](https://user-images.githubusercontent.com/886732/67704936-b65a8980-f9be-11e9-962a-3cab0d510720.png)
