### ISSUE TITLE
How does one change the build name?

### ISSUE THREAD

**Issue by RudolphRiedel** [platformio/platformio-docs#93]
I am using PlatformIO for a windows_x86 command line utility.
And while this works like a charm I can not figure out how to change the default "program.exe" to anything else.

Please expand any of the examples under https://docs.platformio.org/en/latest/platforms/index.html#desktop to demonstrate how to change the build name.

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#custom-firmware-program-name
