### ISSUE TITLE
Does PlatformIO still support CircleCI?

### ISSUE THREAD

**Issue by wz233** [platformio/platformio-docs#94]
I found the tutorial [PlatformIO - CircleCI](https://docs.platformio.org/en/latest/ci/circleci.html) cannot be applied to current CircleCI, and the provided example including Circle [CircleCI example](https://circleci.com/gh/ivankravets/ethercard/tree/master) failed. 

Hope to update this section soon. :) 

Thanks & Regards.

**Comment by ivankravets** [comment]
Please make PR to this page https://github.com/platformio/platformio-docs/blob/develop/ci/circleci.rst

**Comment by wz233** [comment]
I will try to modify part of the document. Thanks.
